GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "Mahiru",
    "email" : "mahiru@gmail.com",
    "password" : "password",
    "confPassword" : "password"
}
